"""add service health daily

Revision ID: 126c8bac0393
Revises: 8ceead7fff65
Create Date: 2026-08-18 22:10:17.584574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126c8bac0393'
down_revision: Union[str, Sequence[str], None] = '8ceead7fff65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_health_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('total_checks', sa.Integer(), nullable=False),
    sa.Column('operational_checks', sa.Integer(), nullable=False),
    sa.Column('degraded_checks', sa.Integer(), nullable=False),
    sa.Column('down_checks', sa.Integer(), nullable=False),
    sa.Column('platform_issue_checks', sa.Integer(), nullable=False),
    sa.Column('unknown_checks', sa.Integer(), nullable=False),
    sa.Column('availability_pct', sa.Float(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('max_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'day', name='uq_service_health_daily_service_day')
    )
    op.create_index(op.f('ix_service_health_daily_day'), 'service_health_daily', ['day'], unique=False)
    op.create_index(op.f('ix_service_health_daily_id'), 'service_health_daily', ['id'], unique=False)
    op.create_index(op.f('ix_service_health_daily_service_id'), 'service_health_daily', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_health_daily_service_id'), table_name='service_health_daily')
    op.drop_index(op.f('ix_service_health_daily_id'), table_name='service_health_daily')
    op.drop_index(op.f('ix_service_health_daily_day'), table_name='service_health_daily')
    op.drop_table('service_health_daily')
    # ### end Alembic commands ###
