"""add health v1 telemetry

Revision ID: 7118f8bb4a80
Revises: 9ea8c13c9494
Create Date: 2026-08-19 07:51:36.538887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7118f8bb4a80'
down_revision: Union[str, Sequence[str], None] = '9ea8c13c9494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_check_events', sa.Column('readiness', sa.String(length=30), nullable=True))
    op.add_column('service_check_events', sa.Column('uptime_seconds', sa.BigInteger(), nullable=True))
    op.add_column('service_check_events', sa.Column('contract_version', sa.String(length=30), nullable=True))
    op.add_column('service_check_events', sa.Column('checks', sa.JSON(), nullable=True))
    op.add_column('service_status', sa.Column('readiness', sa.String(length=30), nullable=True))
    op.add_column('service_status', sa.Column('uptime_seconds', sa.BigInteger(), nullable=True))
    op.add_column('service_status', sa.Column('contract_version', sa.String(length=30), nullable=True))
    op.add_column('service_status', sa.Column('checks', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_status', 'checks')
    op.drop_column('service_status', 'contract_version')
    op.drop_column('service_status', 'uptime_seconds')
    op.drop_column('service_status', 'readiness')
    op.drop_column('service_check_events', 'checks')
    op.drop_column('service_check_events', 'contract_version')
    op.drop_column('service_check_events', 'uptime_seconds')
    op.drop_column('service_check_events', 'readiness')
    # ### end Alembic commands ###
