"""add unknown checks to daily health

Revision ID: 9ea8c13c9494
Revises: 126c8bac0393
Create Date: 2026-08-19 07:05:47.462050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea8c13c9494'
down_revision: Union[str, Sequence[str], None] = '126c8bac0393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_health_daily', sa.Column('unknown_checks', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_health_daily', 'unknown_checks')
    # ### end Alembic commands ###
