"""add service events

Revision ID: f7ab48d0960f
Revises: 7118f8bb4a80
Create Date: 2026-08-19 12:01:32.316647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ab48d0960f'
down_revision: Union[str, Sequence[str], None] = '7118f8bb4a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('current_status', sa.String(length=30), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('source_check_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['source_check_id'], ['service_check_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_service_events_service_occurred_at', 'service_events', ['service_id', sa.literal_column('occurred_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_service_events_service_occurred_at', table_name='service_events')
    op.drop_table('service_events')
    # ### end Alembic commands ###
